### ISSUE TITLE
IMAGENET_TF_WEIGHTS_PATH isn't defined in resnext.py

### ISSUE THREAD

**Issue by hiarindam** [titu1994/Keras-ResNeXt#10]
I'm trying to extract weights from ImageNet for ResNeXt architecture.

While executing resnext.py, I'm receiving below error.

raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

After checking the code in detail I found that the variable IMAGENET_TF_WEIGHTS_PATH is not properly defined, it must contain a valid URL.

Can you please provide your suggestion to resolve this issue?

Thanks.

**Comment by alyato** [comment]
@hiarindam 
Do you download the weight?
thanks.
and @titu1994 how to download the weight?
thanks.

**Comment by titu1994** [comment]
Sadly there are no weights for ResNeXt models. Grouped convoluted layers don't exist yet in Keras or Tensorflow.
