### ISSUE TITLE
Is the model structure in the code the same as in the paper?

### ISSUE THREAD

**Issue by Ostnie** [titu1994/Keras-ResNeXt#11]
Hello，I have read your code and have some doubts about the structure, it seems not tha same as the paper,  especially this part:
I have seen the group conv which has 3*3 kernel, I don't know where is the 1*1 kernel's filters in the resdiual block?

**Comment by titu1994** [comment]
This is an approximate form of the model, which attempts to mimic the grouped conv behavior. Therefore this does not follow the paper architecture in the number of kernels.
