### ISSUE TITLE
Where is ImageNet Weights file?

### ISSUE THREAD

**Issue by LogisticFreedom** [titu1994/Keras-ResNeXt#2]
Thanks for your implementation  of Resnext. But I can't find 'resnext_imagenet_32_4_th_dim_ordering_th_kernels_no_top.h5', I think this file is ImageNet Weight file. How can I get this file? Thank you very much!

**Comment by titu1994** [comment]
Ah sadly I havent been able to port the weights yet. That is just a placeholder name for the weights once I port it. Sorry about that.

**Comment by JoshuaC3** [comment]
Is this still the case? Are there any weights knocking about that we can use for this?

**Comment by salihkaragoz** [comment]
@titu1994  Is there any changes? Do you have ImageNet weights? Thanks in advance...

**Comment by titu1994** [comment]
No. Weight files will probably never be uploaded unless - TF supports grouped convolutional, Keras supports grouped convolutions, and someone ports the caffe weights to a format I can work with. That will take a few months to a year or more. I suggest moving on to more powerful models

**Comment by Henry586** [comment]
That's really a sad news.
