### ISSUE TITLE
cannot import name 'ResNeXt'`

### ISSUE THREAD

**Issue by FerranAlet** [titu1994/Keras-ResNeXt#5]
When running either cifar10.py or cifar100.py I get:

`Using TensorFlow backend.
Traceback (most recent call last):
  File "cifar10.py", line 15, in <module>
    from resnext import hello_ResNeXt
ImportError: cannot import name 'hello_ResNeXt'`

I've checked that I have both tensorflow and keras 2.0.8. I've search on SO but everything I tried didn't solve the issue. One of the things I've tried is putting everything in a single file, but keeps crashing for the same reason.

Any ideas? Thanks!

**Comment by titu1994** [comment]
What is hello_ResNeXt? It's supposed to be from resnext import ResNeXt

**Comment by FerranAlet** [comment]
Sorry @titu1994, I copied an old error from one of my attempts at debugging. The error is essentially the same but ResNeXt.

`Using TensorFlow backend.
Traceback (most recent call last):
  File "cifar10.py", line 15, in <module>
    from resnext import ResNeXt
ImportError: cannot import name 'ResNeXt'
`

**Comment by titu1994** [comment]
That's a name error. It should be ResNext. Not ResNeXt. My bad.

**Comment by FerranAlet** [comment]
Oh wow, I didn't notice either, good catch.
