### ISSUE TITLE
Number of parameters

### ISSUE THREAD

**Issue by ghost** [titu1994/Keras-ResNeXt#6]
when I try to follow the original paper and instantiate CIFAR-10 network (ResNeXt-29, 8x64d), the paper lists 34.4M parameters, but when I run: `ResNext(img_dim, depth=29, cardinality=8, width=64, classes=10)`,
The resulting model summary outputs:
```
Total params: 89,700,288
Trainable params: 89,599,808
Non-trainable params: 100,480
```
What is the reason for the big difference?

**Comment by titu1994** [comment]
Hmm, the cifar mode models are incorrect. I havent found time to fix them, since there is no support for grouped convolutions in Keras or Tensorflow yet.

When support is made available, ill correct the code.
