### ISSUE TITLE
Running out of Memory

### ISSUE THREAD

**Issue by nbansal90** [titu1994/Keras-ResNeXt#7]
Hi, I am running out of memor while running it for CIFAR10, for Cardinality of 8 and Width of 64. I a using Nvidia Ti-1080, for training, with a batch size of 64. Is there any way I can avoid this issue. I tried using multi_gpu option in keras, and that have slowed my training at least 10 times. Any suggestion would be really appreciated

**Comment by titu1994** [comment]
The Keras version is not memory efficient since it doesn't use Grouped Convolutions (doesn't support it yet). Also, try smaller batch sizes, and smaller cardinality - width combination. 

Afaik, 1x64 and 32x4 are best performers.
