### ISSUE TITLE
Different Implementation from paper and original code

### ISSUE THREAD

**Issue by salihkaragoz** [titu1994/Keras-ResNeXt#8]
If you look at the original Resnext code with torch at [facebookresearch/Resnext](https://github.com/facebookresearch/ResNeXt/blob/master/models/resnext.lua) and also in the [paper](https://arxiv.org/pdf/1611.05431.pdf)
You can't see any LeakyReLU activations but you always used LeakyRelu instead of relu. Did you miss that thing or there is different purpose on this? 

Thanks in advance...

**Comment by titu1994** [comment]
I think this is an artifact from an older project. It should he ordinary Relu. I'll update it in some time.

**Comment by titu1994** [comment]
Fixed
